name: flutter_socket_io_chat_call
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^1.0.1
  cupertino_icons: ^1.0.0
  agora_rtc_engine: ^3.2.1
  flutter_socket_io: ^0.6.0
#  permission_handler: ^5.0.1+1
#  permission_handler: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
